export const cities = [
  {
    id: 105813,
    name: "Cordoba",
    region: "Cordoba",
    country: "Argentina",
    lat: -31.4,
    lon: -64.18,
    url: "cordoba-cordoba-argentina",
  },
  {
    id: 705754,
    name: "Cordoba",
    region: "Andalucia",
    country: "Spain",
    lat: 37.88,
    lon: -4.77,
    url: "cordoba-andalucia-spain",
  },
  {
    id: 3165846,
    name: "Cordoba",
    region: "Veracruz-Llave",
    country: "Mexico",
    lat: 18.89,
    lon: -96.93,
    url: "cordoba-veracruz-llave-mexico",
  },
  {
    id: 3165792,
    name: "Cordoba (Santa Leticia)",
    region: "Veracruz-Llave",
    country: "Mexico",
    lat: 18.91,
    lon: -96.98,
    url: "cordoba-santa-leticia-veracruz-llave-mexico",
  },
  {
    id: 505274,
    name: "Cordoba",
    region: "Bolivar Department",
    country: "Colombia",
    lat: 9.59,
    lon: -74.83,
    url: "cordoba-bolivar-department-colombia",
  },
];
